# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  cover:
    - name: "living-room-small"
      unique_id: "living-room-small"
      command_topic: "shutters/living-room-small/set"
      position_topic: "shutters/living-room-small/position"
      state_topic: "shutters/living-room-small/state"
      retain: false
      qos: 2
      state_closed: "state_closed"
      state_closing: "state_closing"
      state_open: "state_opened"
      state_opening: "state_opening"
      state_stopped: "state_stopped"
      set_position_topic: "shutters/living-room-small/set_position"
    - name: "living-room-big"
      unique_id: "living-room-big"
      command_topic: "shutters/living-room-big/set"
      position_topic: "shutters/living-room-big/position"
      state_topic: "shutters/living-room-big/state"
      retain: false
      qos: 2
      state_closed: "state_closed"
      state_closing: "state_closing"
      state_open: "state_opened"
      state_opening: "state_opening"
      state_stopped: "state_stopped"
      set_position_topic: "shutters/living-room-big/set_position"
    - name: "office"
      unique_id: "office"
      command_topic: "shutters/office/set"
      position_topic: "shutters/office/position"
      state_topic: "shutters/office/state"
      retain: false
      qos: 2
      state_closed: "state_closed"
      state_closing: "state_closing"
      state_open: "state_opened"
      state_opening: "state_opening"
      state_stopped: "state_stopped"
      set_position_topic: "shutters/office/set_position"
    - name: "bedroom-1"
      unique_id: "bedroom-1"
      command_topic: "shutters/bedroom-1/set"
      position_topic: "shutters/bedroom-1/position"
      state_topic: "shutters/bedroom-1/state"
      retain: false
      qos: 2
      state_closed: "state_closed"
      state_closing: "state_closing"
      state_open: "state_opened"
      state_opening: "state_opening"
      state_stopped: "state_stopped"
      set_position_topic: "shutters/bedroom-1/set_position"
    - name: "bedroom-2"
      unique_id: "bedroom-2"
      command_topic: "shutters/bedroom-2/set"
      position_topic: "shutters/bedroom-2/position"
      state_topic: "shutters/bedroom-2/state"
      retain: false
      qos: 2
      state_closed: "state_closed"
      state_closing: "state_closing"
      state_open: "state_opened"
      state_opening: "state_opening"
      state_stopped: "state_stopped"
      set_position_topic: "shutters/bedroom-2/set_position"
